# This is a basic workflow to help you get started with Actions

name: ci

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_DDKAAO }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_DDKAAO }}/simplewhale:latest
